module.exports = function() {

  return [

{
  "ramas": {
    "manada": [
      {"numero": 1, "categoria": "Salud y Bienestar", "descripcion": "Elijo alimentos que me ayudan a crecer, estar sano y fuerte.", "icon": "rastro-01.png"},
      {"numero": 2, "categoria": "Salud y Bienestar", "descripcion": "Mantengo una buena higiene personal para tener una vida saludable.", "icon": "rastro-02.png"},
      {"numero": 3, "categoria": "Salud y Bienestar", "descripcion": "Reconozco mis emociones y las expreso entendiendo cómo influyen en mí y en las demás personas.", "icon": "rastro-03.png"},
      {"numero": 4, "categoria": "Salud y Bienestar", "descripcion": "Cuestiono los modelos de cuerpos que veo en los medios de comunicación, en la publicidad, en el deporte y el espectáculo.", "icon": "rastro-04.png"},
      {"numero": 5, "categoria": "Salud y Bienestar", "descripcion": "Valoro y cuido mi cuerpo tal como es para estar saludable y evito comparaciones con el cuerpo de las demás.", "icon": "rastro-05.png"},
      {"numero": 6, "categoria": "Salud y Bienestar", "descripcion": "Expreso mis afectos de manera clara y respetuosa con mis familiares, amigas y amigos.", "icon": "rastro-06.png"},
      {"numero": 7, "categoria": "Salud y Bienestar", "descripcion": "Cuido mi privacidad e intimidad y respeto la de las demás personas.", "icon": "rastro-07.png"},
      {"numero": 8, "categoria": "Salud y Bienestar", "descripcion": "Evito hacer cosas que puedan lastimarme a mí o a otras personas.", "icon": "rastro-08.png"},
      {"numero": 9, "categoria": "Salud y Bienestar", "descripcion": "Me gustan las actividades deportivas y recreativas que comparto con mis amigas y amigos, donde me divierto y juego.", "icon": "rastro-09.png"},
      {"numero": 10, "categoria": "Salud y Bienestar", "descripcion": "Conozco acerca de mi cuerpo (órganos y sistemas), sus funciones y entiendo que es importante cuidar de ellos para sentirme bien.", "icon": "rastro-10.png"},
      {"numero": 11, "categoria": "Paz y Desarrollo", "descripcion": "Ante una pelea o situación de conflicto recurro al diálogo para resolverla.", "icon": "rastro-11.png"},
      {"numero": 12, "categoria": "Paz y Desarrollo", "descripcion": "Me intereso por la cultura de mi comunidad y mi país.", "icon": "rastro-12.png"},
      {"numero": 13, "categoria": "Paz y Desarrollo", "descripcion": "Respeto las diversas tradiciones y expresiones culturales de las colectividades que conforman mi comunidad.", "icon": "rastro-13.png"},
      {"numero": 14, "categoria": "Paz y Desarrollo", "descripcion": "Conozco mi historia, la de mi familia y de mi país.", "icon": "rastro-14.png"},
      {"numero": 15, "categoria": "Paz y Desarrollo", "descripcion": "Conozco mis derechos como niña o niño e identifico cuando estos son vulnerados.", "icon": "rastro-15.png"},
      {"numero": 16, "categoria": "Paz y Desarrollo", "descripcion": "Participó de las decisiones que me involucran y respeto los acuerdos que realizamos.", "icon": "rastro-16.png"},
      {"numero": 17, "categoria": "Paz y Desarrollo", "descripcion": "Comprendo y acepto las reglas y expreso mi opinión sobre ellas.", "icon": "rastro-17.png"},
      {"numero": 18, "categoria": "Paz y Desarrollo", "descripcion": "Participó e incluyo a todas las personas sin discriminarlas.", "icon": "rastro-18.png"},
      {"numero": 19, "categoria": "Paz y Desarrollo", "descripcion": "Realizo acciones solidarias para ayudar a las personas que lo necesitan y mejorar los lugares en donde vivo.", "icon": "rastro-19.png"},
      {"numero": 20, "categoria": "Paz y Desarrollo", "descripcion": "Observo mi entorno con atención para conocer más sobre los problemas que afectan a las personas y sus causas.", "icon": "rastro-20.png"},
      {"numero": 21, "categoria": "Paz y Desarrollo", "descripcion": "Hablo con los demás sobre lo que creo y respeto lo que las otras personas creen.", "icon": "rastro-21.png"},
      {"numero": 22, "categoria": "Paz y Desarrollo", "descripcion": "Comprendo que mis creencias se tienen que notar por la forma en que actúo y soy con las demás personas.", "icon": "rastro-22.png"},
      {"numero": 23, "categoria": "Paz y Desarrollo", "descripcion": "Intento vivir la Ley de la Manada en mis acciones cotidianas.", "icon": "rastro-23.png"},
      {"numero": 24, "categoria": "Ambiente", "descripcion": "Cuido del planeta utilizando los recursos de forma responsable sin desperdiciar.", "icon": "rastro-24.png"},
      {"numero": 25, "categoria": "Ambiente", "descripcion": "Colaboro con otras personas en acciones de cuidado del planeta.", "icon": "rastro-25.png"},
      {"numero": 26, "categoria": "Ambiente", "descripcion": "Identifico algunos problemas ambientales de mi comunidad y las causas que los provocan.", "icon": "rastro-26.png"},
      {"numero": 27, "categoria": "Ambiente", "descripcion": "Comprendo que en la naturaleza todo está relacionado y me comprometo a realizar acciones para mantenerla saludable y en equilibrio.", "icon": "rastro-27.png"},
      {"numero": 28, "categoria": "Ambiente", "descripcion": "Entiendo que mis acciones tienen un impacto en el Planeta Tierra y me comprometo a su cuidado.", "icon": "rastro-28.png"},
      {"numero": 29, "categoria": "Ambiente", "descripcion": "Disfruto de descubrir la diversidad que existe en la naturaleza.", "icon": "rastro-29.png"},
      {"numero": 30, "categoria": "Ambiente", "descripcion": "Desarrollo habilidades que me permiten disfrutar de la naturaleza.", "icon": "rastro-30.png"},
      {"numero": 31, "categoria": "Ambiente", "descripcion": "Descubro las maravillas de la naturaleza y me asombro por la grandeza y belleza que me rodea.", "icon": "rastro-31.png"},
      {"numero": 32, "categoria": "Habilidades para la Vida", "descripcion": "Me intereso por aprender cosas nuevas.", "icon": "rastro-32.png"},
      {"numero": 33, "categoria": "Habilidades para la Vida", "descripcion": "Utilizo diferentes herramientas y busco soluciones para resolver situaciones cotidianas.", "icon": "rastro-33.png"},
      {"numero": 34, "categoria": "Habilidades para la Vida", "descripcion": "Me enfrento a desafíos y problemas y encuentro soluciones creativas para resolverlos.", "icon": "rastro-34.png"},
      {"numero": 35, "categoria": "Habilidades para la Vida", "descripcion": "Conozco diferentes profesiones y oficios.", "icon": "rastro-35.png"},
      {"numero": 36, "categoria": "Habilidades para la Vida", "descripcion": "Descubro mis intereses y habilidades realizando pasatiempos y especialidades.", "icon": "rastro-36.png"},
      {"numero": 37, "categoria": "Habilidades para la Vida", "descripcion": "Me responsabilizo por distintas tareas en mi Manada y seisena.", "icon": "rastro-37.png"},
      {"numero": 38, "categoria": "Habilidades para la Vida", "descripcion": "Desempeño el rol de seisenera o seisenero y apoyo a otras lobeznas y otros lobatos para que lo hagan.", "icon": "rastro-38.png"},
      {"numero": 39, "categoria": "Habilidades para la Vida", "descripcion": "Uso programas y aplicaciones que me ayudan en mi vida cotidiana.", "icon": "rastro-39.png"},
      {"numero": 40, "categoria": "Habilidades para la Vida", "descripcion": "Busco información en diferentes fuentes (libros, revistas, sitios web, videos, etc.) y me aseguro de que sea útil y verdadera antes de usarla o compartirla.", "icon": "rastro-40.png"},
      {"numero": 41, "categoria": "Habilidades para la Vida", "descripcion": "Soy responsable en el uso de los dispositivos tecnológicos y los utilizo de manera segura.", "icon": "rastro-41.png"},
      {"numero": 42, "categoria": "Habilidades para la Vida", "descripcion": "Sé usar el dinero y utilizar mis recursos de manera responsable.", "icon": "rastro-42.png"},
      {"numero": 43, "categoria": "Habilidades para la Vida", "descripcion": "Organizo mis tiempos en las distintas actividades y responsabilidades, teniendo en cuenta mi tiempo libre y de juego.", "icon": "rastro-43.png"},
      {"numero": 44, "categoria": "Habilidades para la Vida", "descripcion": "Me propongo tareas que ayudan a superar mis dificultades.", "icon": "rastro-44.png"},
      {"numero": 45, "categoria": "Habilidades para la Vida", "descripcion": "Pido ayuda y también ayudo a los demás para enfrentar algunas dificultades.", "icon": "rastro-45.png"},
      {"numero": 46, "categoria": "Habilidades para la Vida", "descripcion": "Expreso mis ideas de forma clara y amable, y escucho a los demás con atención y respeto.", "icon": "rastro-46.png"},
      {"numero": 47, "categoria": "Habilidades para la Vida", "descripcion": "Expreso mis emociones y sentimientos a través de diversos medios artísticos.", "icon": "rastro-47.png"}
    ],
    "scouts": [
      {"numero": 1, "categoria": "Salud y Bienestar", "descripcion": "Incorporo hábitos de higiene."},
      {"numero": 2, "categoria": "Salud y Bienestar", "descripcion": "Entiendo la importancia de alimentarme de forma saludable."},
      {"numero": 3, "categoria": "Salud y Bienestar", "descripcion": "Reconozco y expreso mis emociones, entendiendo cómo me afectan a mí y a las demás personas."},
      {"numero": 4, "categoria": "Salud y Bienestar", "descripcion": "Soy crítica/o con las imágenes y mensajes que los medios de comunicación y las redes sociales nos presentan sobre los modelos corporales y las modas."},
      {"numero": 5, "categoria": "Salud y Bienestar", "descripcion": "Busco información y tomo decisiones conscientes para cuidar mi salud y sentirme bien conmigo misma/o."},
      {"numero": 6, "categoria": "Salud y Bienestar", "descripcion": "Acepto y valoro mi cuerpo y el de los demás, evitando comparaciones."},
      {"numero": 7, "categoria": "Salud y Bienestar", "descripcion": "Reconozco e identifico las particularidades, diferencias y cambios de mi cuerpo a medida que voy creciendo."},
      {"numero": 8, "categoria": "Salud y Bienestar", "descripcion": "Identifico y respeto mis emociones y sentimientos vinculados a la sexualidad y sus cambios."},
      {"numero": 9, "categoria": "Salud y Bienestar", "descripcion": "Valoro el diálogo y el respeto mutuo en mis relaciones, expresando mi opinión de manera segura y respetuosa."},
      {"numero": 10, "categoria": "Salud y Bienestar", "descripcion": "Conozco los recursos y lugares donde puedo obtener información y apoyo para proteger mis derechos sexuales."},
      {"numero": 11, "categoria": "Salud y Bienestar", "descripcion": "Descubro los beneficios que tiene la actividad física y los deportes para mi bienestar físico y emocional."},
      {"numero": 12, "categoria": "Salud y Bienestar", "descripcion": "Trabajo en equipo y disfruto de las actividades físicas y deportivas, fomentando el desarrollo social y emocional."},
      {"numero": 13, "categoria": "Salud y Bienestar", "descripcion": "Identifico situaciones de riesgo y adopto prácticas seguras."},
      {"numero": 14, "categoria": "Salud y Bienestar", "descripcion": "Conozco y construyo redes de apoyo y ayuda mutua."},
      {"numero": 15, "categoria": "Paz y Desarrollo", "descripcion": "Colaboro en la resolución de situaciones de conflicto a través del diálogo, evitando situaciones de violencia, en los espacios donde me desenvuelvo."},
      {"numero": 16, "categoria": "Paz y Desarrollo", "descripcion": "Exploro y me identifico con la cultura de mi comunidad y de mi país proponiendo actividades y proyectos con esta temática."},
      {"numero": 17, "categoria": "Paz y Desarrollo", "descripcion": "Valoro mi historia e identidad, la de mi País y respeto sus símbolos patrios."},
      {"numero": 18, "categoria": "Paz y Desarrollo", "descripcion": "Valoro y respeto la importancia de los Derechos Humanos en la sociedad e identifico situaciones de vulneración de estos, buscando activamente ayuda en mi entorno."},
      {"numero": 19, "categoria": "Paz y Desarrollo", "descripcion": "Ejercito y promuevo prácticas que fomenten la participación democrática en los diferentes contextos en donde me desenvuelvo."},
      {"numero": 20, "categoria": "Paz y Desarrollo", "descripcion": "Respeto los acuerdos de convivencia y las decisiones tomadas por los demás, expresando mis propias ideas y posturas de manera empática y respetuosa."},
      {"numero": 21, "categoria": "Paz y Desarrollo", "descripcion": "Promuevo que se garanticen los derechos de todas las personas en los ámbitos en los que participo."},
      {"numero": 22, "categoria": "Paz y Desarrollo", "descripcion": "Fomento el respeto a la diversidad en todas sus formas, cuestionando estereotipos y prejuicios en mis interacciones diarias."},
      {"numero": 23, "categoria": "Paz y Desarrollo", "descripcion": "Promuevo la participación e inclusión de todas las personas, sin discriminación alguna."},
      {"numero": 24, "categoria": "Paz y Desarrollo", "descripcion": "Identifico oportunidades para ayudar a alguien de manera individual y/o colectiva, sin esperar nada a cambio."},
      {"numero": 25, "categoria": "Paz y Desarrollo", "descripcion": "Me comprometo y animo a otras personas a trabajar en conjunto para lograr un cambio positivo en el mundo."},
      {"numero": 26, "categoria": "Paz y Desarrollo", "descripcion": "Observo lo que pasa a mi alrededor y trato de entender las razones detrás de las desigualdades que veo, actuando de manera responsable en situaciones que afectan a la sociedad, contribuyendo a mejorar el bienestar de las personas."},
      {"numero": 27, "categoria": "Paz y Desarrollo", "descripcion": "Me pregunto sobre el origen, la grandeza, belleza y misterios de todo lo que soy, somos y nos rodea."},
      {"numero": 28, "categoria": "Paz y Desarrollo", "descripcion": "Dialogo con los demás sobre lo que creo y busco conocer lo que los otros creen, demostrando respeto e interés."},
      {"numero": 29, "categoria": "Paz y Desarrollo", "descripcion": "Adhiero a los valores expresados en la Ley y la Promesa Scout comprendiendo su importancia para mi vida."},
      {"numero": 30, "categoria": "Paz y Desarrollo", "descripcion": "Me pregunto sobre mis creencias, prioridades, valores y cómo se manifiesta en mi actuar cotidiano."},
      {"numero": 31, "categoria": "Ambiente", "descripcion": "Reconozco mi impacto en el ambiente y en la sociedad, adoptando un estilo de vida responsable y sostenible."},
      {"numero": 32, "categoria": "Ambiente", "descripcion": "Utilizo los recursos naturales de forma consciente y busco alternativas que promuevan la conservación del ambiente."},
      {"numero": 33, "categoria": "Ambiente", "descripcion": "Participó de iniciativas para construir una sociedad más respetuosa con el planeta."},
      {"numero": 34, "categoria": "Ambiente", "descripcion": "Comprendo las causas y consecuencias del impacto ambiental y realizo acciones para preservar y proteger el ambiente."},
      {"numero": 35, "categoria": "Ambiente", "descripcion": "Comprendo que todo lo que le hacemos a los seres vivos y al ambiente nos afecta recíprocamente."},
      {"numero": 36, "categoria": "Ambiente", "descripcion": "Entiendo que la Tierra es un lugar precioso y único en el universo, y que todos tenemos la responsabilidad de protegerla y mantenerla saludable."},
      {"numero": 37, "categoria": "Ambiente", "descripcion": "Exploro oportunidades junto a mis amigas y amigos para conectarme con la naturaleza, cuidándola y protegiéndola, ya sea en mi comunidad local o en lugares más lejanos."},
      {"numero": 38, "categoria": "Ambiente", "descripcion": "Desarrollo habilidades y técnicas que me permitan el disfrute de la vida en la naturaleza."},
      {"numero": 39, "categoria": "Ambiente", "descripcion": "Exploro y contemplo la naturaleza como un espacio que me permite el bienestar para mí, ayudándome a conectar con lo trascendente."},
      {"numero": 40, "categoria": "Habilidades para la Vida", "descripcion": "Exploro temas de mi interés con la intención de mejorar cada día."},
      {"numero": 41, "categoria": "Habilidades para la Vida", "descripcion": "Experimento diferentes medios y tecnologías que me ayuden a resolver problemas de la vida cotidiana."},
      {"numero": 42, "categoria": "Habilidades para la Vida", "descripcion": "Aplico mi conocimiento y habilidades para resolver los desafíos y oportunidades que se me presentan."},
      {"numero": 43, "categoria": "Habilidades para la Vida", "descripcion": "Comparto mis pasatiempos y especialidades con amigas y amigos, buscando intereses comunes que podamos desarrollar en conjunto."},
      {"numero": 44, "categoria": "Habilidades para la Vida", "descripcion": "Asumo un rol de manera responsable en los proyectos y/o actividades de mi Patrulla y/o Unidad."},
      {"numero": 45, "categoria": "Habilidades para la Vida", "descripcion": "Lidero actividades y proyectos, acompañando y motivando a mis pares a sumarse."},
      {"numero": 46, "categoria": "Habilidades para la Vida", "descripcion": "Exploro y experimento con diferentes técnicas y tecnologías para resolver problemas, lograr mis objetivos y descubrir soluciones creativas."},
      {"numero": 47, "categoria": "Habilidades para la Vida", "descripcion": "Busco información en diversas fuentes, y evalúo su veracidad y relevancia antes de aplicarla de manera crítica y creativa en diferentes situaciones y contextos."},
      {"numero": 48, "categoria": "Habilidades para la Vida", "descripcion": "Comprendo la importancia de ser responsable y ético en el uso de la tecnología y la información."},
      {"numero": 49, "categoria": "Habilidades para la Vida", "descripcion": "Administro mis recursos y mi dinero de forma responsable."},
      {"numero": 50, "categoria": "Habilidades para la Vida", "descripcion": "Organizo mi tiempo en forma adecuada diferenciando mis responsabilidades de mi tiempo libre."},
      {"numero": 51, "categoria": "Habilidades para la Vida", "descripcion": "Enfrento y supero las dificultades que se me presentan y aprendo de la experiencia."},
      {"numero": 52, "categoria": "Habilidades para la Vida", "descripcion": "Desarrollo habilidades para comunicarme claramente con otros; escuchar y valorar sus ideas, trabajando juntos para lograr nuestras metas."},
      {"numero": 53, "categoria": "Habilidades para la Vida", "descripcion": "Participó de diferentes manifestaciones artísticas en las que expreso mis emociones y sentimientos."}
    ],
    "caminantes": [
      {"numero": 1, "categoria": "Salud y Bienestar", "descripcion": "Adopto y promuevo hábitos de alimentación e higiene saludables."},
      {"numero": 2, "categoria": "Salud y Bienestar", "descripcion": "Expreso mis emociones entendiendo cómo me afectan a mí e influyen en mi entorno."},
      {"numero": 3, "categoria": "Salud y Bienestar", "descripcion": "Adopto una mirada crítica sobre las imágenes y mensajes que los medios de comunicación y las redes sociales nos muestran acerca de los cuerpos y las apariencias."},
      {"numero": 4, "categoria": "Salud y Bienestar", "descripcion": "Acepto mi cuerpo tal y como es, sin compararlo con el de las demás personas, entendiendo que es único y valioso."},
      {"numero": 5, "categoria": "Salud y Bienestar", "descripcion": "Respeto y promuevo el respeto sobre la diversidad de identidades y géneros, sin prejuicios ni discriminación."},
      {"numero": 6, "categoria": "Salud y Bienestar", "descripcion": "Comprendo que mi sexualidad es una parte importante de mi vida individual y junto a otras personas."},
      {"numero": 7, "categoria": "Salud y Bienestar", "descripcion": "Me informo y tomo decisiones responsables sobre mi salud sexual, cuidando de mí y de las demás personas, para disfrutar de relaciones sanas y seguras."},
      {"numero": 8, "categoria": "Salud y Bienestar", "descripcion": "Valoro el diálogo y respeto mutuo para mantener relaciones de confianza y afecto."},
      {"numero": 9, "categoria": "Salud y Bienestar", "descripcion": "Sé a dónde recurrir para proteger mis derechos sexuales y reproductivos obteniendo los recursos necesarios para vivir mi sexualidad con responsabilidad."},
      {"numero": 10, "categoria": "Salud y Bienestar", "descripcion": "Me involucro en actividades físicas y deportivas como parte fundamental de mi bienestar, explorando mi potencial y desafiándome a mí mismo/a."},
      {"numero": 11, "categoria": "Salud y Bienestar", "descripcion": "Comparto actividades recreativas, deportivas y lúdicas, fomentando mi desarrollo social y emocional junto a mis amistades."},
      {"numero": 12, "categoria": "Salud y Bienestar", "descripcion": "Tomo decisiones responsables evitando acciones que puedan poner en riesgo mi seguridad y bienestar, así como el de las personas que me rodean."},
      {"numero": 13, "categoria": "Salud y Bienestar", "descripcion": "Me informo y preparo para enfrentar situaciones de emergencia."},
      {"numero": 14, "categoria": "Salud y Bienestar", "descripcion": "Conozco, construyo y promociono redes de apoyo y ayuda mutua junto a mis pares."},
      {"numero": 15, "categoria": "Paz y Desarrollo", "descripcion": "Contribuyo pacíficamente a la resolución de conflictos evitando toda forma de intolerancia y violencia."},
      {"numero": 16, "categoria": "Paz y Desarrollo", "descripcion": "Valoro mi historia e identidad y promuevo la herencia cultural de mi comunidad y país (costumbres, leyendas, danzas, mitos, artesanías, tradiciones)."},
      {"numero": 17, "categoria": "Paz y Desarrollo", "descripcion": "Desarrollo estrategias para promover y difundir los Derechos Humanos."},
      {"numero": 18, "categoria": "Paz y Desarrollo", "descripcion": "Ejercito plena y responsablemente mis derechos como ciudadano y los promuevo en todos los ámbitos en donde me desarrollo, con una mirada crítica de la realidad."},
      {"numero": 19, "categoria": "Paz y Desarrollo", "descripcion": "Fomento ámbitos de participación democráticos, respetando las decisiones tomadas sin renunciar a mi derecho a luchar por su cambio."},
      {"numero": 20, "categoria": "Paz y Desarrollo", "descripcion": "Defiendo colectivamente los Derechos de las infancias, juventudes y mujeres y promuevo acciones que contribuyan a garantizarlos."},
      {"numero": 21, "categoria": "Paz y Desarrollo", "descripcion": "Cuestiono mis prejuicios y estereotipos culturales entendiendo cómo estos influyen en las interacciones con otras personas."},
      {"numero": 22, "categoria": "Paz y Desarrollo", "descripcion": "Trabajo activamente para facilitar y promover la participación e inclusión de todas las personas en mis actividades."},
      {"numero": 23, "categoria": "Paz y Desarrollo", "descripcion": "Me involucro de forma empática y activa, en acciones solidarias en la comunidad."},
      {"numero": 24, "categoria": "Paz y Desarrollo", "descripcion": "Me preocupo por las personas que me rodean, sus necesidades y busco maneras de hacer una diferencia positiva en sus vidas."},
      {"numero": 25, "categoria": "Paz y Desarrollo", "descripcion": "Identifico y analizo los factores que contribuyen a la existencia de problemas sociales, desarrollando una actitud crítica, actuando de manera coherente y responsable en mi entorno."},
      {"numero": 26, "categoria": "Paz y Desarrollo", "descripcion": "Me cuestiono sobre las posturas respecto al origen, la grandeza, belleza y misterios de todo lo que soy, somos y nos rodea."},
      {"numero": 27, "categoria": "Paz y Desarrollo", "descripcion": "Dialogo con las demás personas sobre lo que creo, promoviendo el entendimiento."},
      {"numero": 28, "categoria": "Paz y Desarrollo", "descripcion": "Reconozco cómo mis creencias, prioridades y valores influyen en mis decisiones cotidianas para vivir de manera auténtica y coherente con lo que creo y valoro."},
      {"numero": 29, "categoria": "Ambiente", "descripcion": "Adopto un estilo de vida responsable y sostenible en mi consumo y producción."},
      {"numero": 30, "categoria": "Ambiente", "descripcion": "Me posiciono de manera crítica y responsable sobre las decisiones con impacto ambiental y realizo acciones al respecto."},
      {"numero": 31, "categoria": "Ambiente", "descripcion": "Soy consciente sobre la conexión e interdependencia entre todos los seres vivos, esforzándome por vivir en armonía."},
      {"numero": 32, "categoria": "Ambiente", "descripcion": "Entiendo que la Tierra es nuestra casa común y que tenemos la responsabilidad de protegerla para las generaciones presentes y futuras."},
      {"numero": 33, "categoria": "Ambiente", "descripcion": "Descubro y valoro la belleza y diversidad de la naturaleza disfrutando de las aventuras que puedo vivir en ella."},
      {"numero": 34, "categoria": "Ambiente", "descripcion": "Aprovecho toda oportunidad como un desafío para conectar con el mundo natural, cuidándolo y protegiéndolo."},
      {"numero": 35, "categoria": "Ambiente", "descripcion": "Reconozco a la naturaleza como una fuente de bienestar para mí y de conexión con lo trascendente."},
      {"numero": 36, "categoria": "Habilidades para la Vida", "descripcion": "Trabajo en mi superación personal, enfocándome en mis intereses personales."},
      {"numero": 37, "categoria": "Habilidades para la Vida", "descripcion": "Investigo y desarrollo distintas habilidades y tecnologías, que me permitan adquirir experiencias prácticas y útiles para mi vida."},
      {"numero": 38, "categoria": "Habilidades para la Vida", "descripcion": "Afronto creativamente los desafíos y problemas que se me presentan y aporto soluciones innovadoras."},
      {"numero": 39, "categoria": "Habilidades para la Vida", "descripcion": "Me informo, exploro y experimento sobre las distintas opciones dentro del mundo del trabajo en función a mis intereses."},
      {"numero": 40, "categoria": "Habilidades para la Vida", "descripcion": "Motivo y oriento a otras personas a trabajar en conjunto para lograr objetivos comunes."},
      {"numero": 41, "categoria": "Habilidades para la Vida", "descripcion": "Apoyo a otras personas para colaborar en el desarrollo de su liderazgo."},
      {"numero": 42, "categoria": "Habilidades para la Vida", "descripcion": "Aplico técnicas y tecnologías disponibles en la vida cotidiana."},
      {"numero": 43, "categoria": "Habilidades para la Vida", "descripcion": "Busco y evalúo el valor de diversas fuentes de información (académicas, científicas, artísticas, populares, empíricas, ancestrales, etc.) y las aplico de manera crítica y creativa en función de la necesidad y los contextos."},
      {"numero": 44, "categoria": "Habilidades para la Vida", "descripcion": "Planifico y administro responsablemente mis recursos, de forma ética."},
      {"numero": 45, "categoria": "Habilidades para la Vida", "descripcion": "Establezco prioridades en las tareas administrando el uso del tiempo y los recursos disponibles para lograr los objetivos."},
      {"numero": 46, "categoria": "Habilidades para la Vida", "descripcion": "Encuentro momentos para descansar, distenderme, compartir con mis amistades y disfrutar de mi tiempo libre."},
      {"numero": 47, "categoria": "Habilidades para la Vida", "descripcion": "Actúo de manera resiliente ante las dificultades, buscando la superación personal y colectiva."},
      {"numero": 48, "categoria": "Habilidades para la Vida", "descripcion": "Desarrollo habilidades para comunicarme de forma efectiva y respetuosa, influyendo positivamente en mi entorno y en la sociedad en general."},
      {"numero": 49, "categoria": "Habilidades para la Vida", "descripcion": "Utilizo diferentes herramientas y tecnologías de comunicación para llegar a un público más amplio y diverso, promoviendo el diálogo y la colaboración entre las personas."}
    ],
    "rovers": [
      {"numero": 1, "ruta": "Corporalidad", "numero_original": 1, "descripcion": "Sostengo y promuevo hábitos de higiene y alimentación saludables."},
      {"numero": 2, "ruta": "Corporalidad", "numero_original": 2, "descripcion": "Disfruto y participo de las actividades recreativas, lúdicas, físicas y deportivas, buscando mi bienestar integral."},
      {"numero": 3, "ruta": "Corporalidad", "numero_original": 3, "descripcion": "Organizo y administro el tiempo y los recursos disponibles para alcanzar mis metas."},
      {"numero": 4, "ruta": "Corporalidad", "numero_original": 4, "descripcion": "Disfruto de las oportunidades y experiencias que brinda la vida en la naturaleza."},
      {"numero": 5, "ruta": "Corporalidad", "numero_original": 5, "descripcion": "Evalúo situaciones y busco evitar conductas que me expongan a peligros a mí o a otras personas."},
      {"numero": 6, "ruta": "Creatividad", "numero_original": 1, "descripcion": "Exploro mis intereses vocacionales, descubro mis posibilidades y elijo en consecuencia."},
      {"numero": 7, "ruta": "Creatividad", "numero_original": 2, "descripcion": "Aplico técnicas y tecnologías de la información disponibles en la vida cotidiana."},
      {"numero": 8, "ruta": "Creatividad", "numero_original": 3, "descripcion": "Busco y evalúo el valor de diversas fuentes de información (académicas, científicas, artísticas, populares, empíricas, ancestrales, etc.) y las aplico de manera crítica y creativa en función de la necesidad y los contextos."},
      {"numero": 9, "ruta": "Creatividad", "numero_original": 4, "descripcion": "Me posiciono crítica y responsablemente ante los mensajes que los medios de comunicación y redes sociales instalan sobre el cuerpo humano y sus estereotipos."},
      {"numero": 10, "ruta": "Afectividad", "numero_original": 1, "descripcion": "Contribuyo pacíficamente a la resolución de conflictos evitando toda forma de intolerancia y violencia, promoviendo la paz."},
      {"numero": 11, "ruta": "Afectividad", "numero_original": 2, "descripcion": "Me comunico de manera asertiva y comprensible utilizando diferentes formatos y medios con una mirada inclusiva."},
      {"numero": 12, "ruta": "Afectividad", "numero_original": 3, "descripcion": "Me comunico de manera asertiva y comprensible utilizando diferentes formatos y medios en una mirada inclusiva."},
      {"numero": 13, "ruta": "Afectividad", "numero_original": 4, "descripcion": "Tomo consciencia de mis emociones y las expreso comprendiendo como impactan en mí y en mi entorno."},
      {"numero": 14, "ruta": "Afectividad", "numero_original": 5, "descripcion": "Reconozco, acepto y valoro mi cuerpo y el de los demás en su integralidad."},
      {"numero": 15, "ruta": "Afectividad", "numero_original": 6, "descripcion": "Vivo mi sexualidad de manera plena y consciente cuidando mis relaciones sexoafectivas de manera sana y segura."},
      {"numero": 16, "ruta": "Afectividad", "numero_original": 7, "descripcion": "Analizo y cuestiono actitudes y estereotipos culturales entendiendo cómo éstas pueden perpetuar la discriminación y exclusión."},
      {"numero": 17, "ruta": "Carácter", "numero_original": 1, "descripcion": "Me responsabilizo por mi desarrollo personal, esforzándome por superarme constantemente."},
      {"numero": 18, "ruta": "Carácter", "numero_original": 2, "descripcion": "Desarrollo habilidades para el mundo laboral."},
      {"numero": 19, "ruta": "Carácter", "numero_original": 3, "descripcion": "Tomo decisiones económicas (y financieras) que acompañen mi proyecto de vida de manera consciente y responsable."},
      {"numero": 20, "ruta": "Carácter", "numero_original": 4, "descripcion": "Actúo de manera resiliente ante las dificultades, buscando la superación personal y colectiva."},
      {"numero": 21, "ruta": "Sociabilidad", "numero_original": 1, "descripcion": "Valoro mi identidad y promuevo la herencia cultural, rescatando los saberes ancestrales de mi comunidad y de mi país."},
      {"numero": 22, "ruta": "Sociabilidad", "numero_original": 2, "descripcion": "Promuevo y defiendo los Derechos Humanos."},
      {"numero": 23, "ruta": "Sociabilidad", "numero_original": 3, "descripcion": "Ejercito plena y responsablemente mis derechos como ciudadano/a en todos los ámbitos de desarrollo con una mirada crítica de la realidad."},
      {"numero": 24, "ruta": "Sociabilidad", "numero_original": 4, "descripcion": "Defiendo y promuevo el respeto a las reglas de la democracia, aportando a su construcción a partir de una mirada crítica de la realidad."},
      {"numero": 25, "ruta": "Sociabilidad", "numero_original": 5, "descripcion": "Miro al mundo desde una perspectiva de derechos, viviendo y promoviendo colectivamente una experiencia integral, igualitaria y segura."},
      {"numero": 26, "ruta": "Sociabilidad", "numero_original": 6, "descripcion": "Valoro la diversidad y promuevo la inclusión en todos los ámbitos en los que me desempeño."},
      {"numero": 27, "ruta": "Sociabilidad", "numero_original": 7, "descripcion": "Me involucro, planifico y desarrollo acciones comunitarias que sean sostenibles y tengan un impacto socioambiental positivo."},
      {"numero": 28, "ruta": "Sociabilidad", "numero_original": 8, "descripcion": "Valoro y promuevo la solidaridad, la empatía y el compromiso social como formas esenciales de vivir junto a las demás personas."},
      {"numero": 29, "ruta": "Sociabilidad", "numero_original": 9, "descripcion": "Indago en las causas y consecuencias de las injusticias, desigualdades y problemáticas sociales, actuando comprometida y coherentemente para la construcción de una sociedad cada vez más justa, equitativa e igualitaria."},
      {"numero": 30, "ruta": "Sociabilidad", "numero_original": 10, "descripcion": "Consumo y produzco de manera sostenible y sustentable."},
      {"numero": 31, "ruta": "Sociabilidad", "numero_original": 11, "descripcion": "Desarrollo acciones de preservación y protección ambiental a partir de una conciencia crítica y responsable de las causas y consecuencias del impacto ambiental."},
      {"numero": 32, "ruta": "Sociabilidad", "numero_original": 12, "descripcion": "Reconozco la interdependencia entre las personas y todas las especies desarrollando el cuidado de la madre tierra."},
      {"numero": 33, "ruta": "Sociabilidad", "numero_original": 13, "descripcion": "Reconozco que la Tierra es nuestra casa común y promuevo la armonía con la naturaleza, a favor de un equilibrio justo entre las necesidades económicas, sociales y ambientales de las generaciones actuales y futuras."},
      {"numero": 34, "ruta": "Espiritualidad", "numero_original": 1, "descripcion": "Me cuestiono sobre las grandes preguntas que dan sentido a la existencia."},
      {"numero": 35, "ruta": "Espiritualidad", "numero_original": 2, "descripcion": "Promuevo el diálogo y el entendimiento más allá de las creencias personales."},
      {"numero": 36, "ruta": "Espiritualidad", "numero_original": 3, "descripcion": "Asumo un estilo de vida en coherencia con mis creencias y valores."},
      {"numero": 37, "ruta": "Espiritualidad", "numero_original": 4, "descripcion": "Valoro la naturaleza como una oportunidad de conexión conmigo mismo y con lo trascendente."}
    ]
  }
}


  ];

};
